version: '3.8'

services:
  ms2-estudiantes-matriculas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms2-estudiantes-matriculas
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - educativa-network

networks:
  educativa-network:
    driver: bridge