version: '3.8'

services:
  # Servicio MySQL
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: utec
      MYSQL_DATABASE: demomysql
    ports:
      - "3307:3306"  # host:container
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -putec || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - educativa-network

  # Microservicio MS2
  ms2-estudiantes-matriculas:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ms2-estudiantes-matriculas
    ports:
      - "8082:8082"
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - educativa-network

networks:
  educativa-network:
    driver: bridge

volumes:
  mysql_data:
